### ISSUE TITLE
Nominate Meenal as recurrent contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#21]
I'd like to nominate @mjhajharia to be a recurrent contributor at ArviZ.

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) role.

---

Meenal has already done a couple contributions to arviz repo and we also discussed the scope and potential api of xarray-einstats before I got started with it. I think it will be great to have her on slack so she can participate and better coordinate going further.

**Comment by mjhajharia** [comment]
thanks, I'd love to be more involved and help out however I can, I accept!

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome!

Can you reach out to `arvizdevs (at) gmail (dot) com` with the email you'd like us to use when adding you to the ArviZ slack?

**Comment by mjhajharia** [comment]
done!

**Comment by OriolAbril** [comment]
@mjhajharia there might have been a typo on the email. I can't find your message on arviz's email account

**Comment by mjhajharia** [comment]
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/55153708/188929848-e9336dcc-61ba-43d1-a662-7889a8b1272b.png">

is this is the right email?

**Comment by OriolAbril** [comment]
Invite sent, as expected, the email ended up on spam somehow, sorry.
