### ISSUE TITLE
Nominate Sandra as recurrent contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#22]
I'd like to nominate @symeneses to be a recurrent contributor at ArviZ.

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) role.

---

Sandra has already done a few PRs to arviz repo, reviewed a couple more and we have also had multiple discussions about the ArviZ community structure and activities.

**Comment by symeneses** [comment]
Thanks for considering me. 😊
I agree. ✍🏽

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome!

Can you reach out to `arvizdevs (at) gmail (dot) com` with the email you'd like us to use when adding you to the ArviZ slack?

**Comment by symeneses** [comment]
Thanks your Oriol! Indeed good news.
Hope to be able to contribute in the best way possible 💪🏽
