### ISSUE TITLE
Nominate Jacki as recurrent contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#23]
I'd like to nominate @jburos to be a recurrent contributor at ArviZ.

To @jburos:

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) role.

---

To @arviz-devs/rv_council members:

Jacki has been very helpful in many issues for a very long time and also did a PR not long ago. I think she would be a great addition as she has a lot of experience and insights that will help the project.

**Comment by jburos** [comment]
Thanks for the nomination @OriolAbril - would be happy to contribute and participate in this role if approved

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome!

Can you reach out to `arvizdevs (at) gmail (dot) com` with the email you'd like us to use when adding you to the ArviZ slack?
