### ISSUE TITLE
Nominate Gayathri as recurrent contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#24]
I'd like to nominate @gayathri-krishnaswamy to be a recurrent contributor at ArviZ.

To @gayathri-krishnaswamy:

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) role.

---

To @arviz-devs/rv_council members:

Gayathri did a great PR to improve the contributing index page of the documentation and also has many other ideas for doc structure and doc content. It will be great to be able to discuss all this in slack.

**Comment by gayathri-krishnaswamy** [comment]
Thanks for the nomination! I accept it.

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome!

Can you reach out to `arvizdevs (at) gmail (dot) com` with the email you'd like us to use when adding you to the ArviZ slack?
