### ISSUE TITLE
 Nominate Alejandro Icazatti as recurrent contributor

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz-project#26]
I'd like to nominate @aleicazatti to be a recurrent contributor at ArviZ.

To @aleicazatti:
Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you to accept the nomination, which you can do commenting on this issue.
If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process)
(in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the
[recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) role.

To https://github.com/orgs/arviz-devs/teams/rv_council members:

Ale has already submitted two PR adding new distributions to PreliZ and we both have been discussing how to improve PreliZ in order to make a first release and beyond. He may also contribute in the future to the ArviZ package, one possible feature could be better SMC integration (but this is still under discussion).

**Comment by aleicazatti** [comment]
I accept the nomination. Thank you very much.

**Comment by OriolAbril** [comment]
Sorry about the late answer. Very excited to announce that the RV council voted and accepted the nomination! Welcome!

Can you reach out to arvizdevs (at) gmail (dot) com with the email you'd like us to use when adding you to the ArviZ slack (all channels)? 

I will also open an issue to this repo to add you to https://www.arviz.org/en/latest/our_team.html#recurrent-contributors. Do you prefer we use your name+surname, github handle...? We generally use name+surname but it is nor required

**Comment by aleicazatti** [comment]
Thank you very much! 

I have sent the email for slack, and with respect to the recurrent contributors page, I prefer to use my name+surname: Alejandro Icazatti

**Comment by OriolAbril** [comment]
Invite sent and PR opened, I'll close and lock the issue now.
