### ISSUE TITLE
Nominate Xiaoyan as recurrent contributor

### ISSUE THREAD

**Issue by ndmlny-qs** [arviz-devs/arviz-project#29]
I'd like to nominate Xiaoyan (@horizon-blue) to be a recurrent contributor at ArviZ.

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you to accept the nomination which you can do commenting on this issue.
If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) and [core contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#core-contributors)
role.

---

For the members,

Xiaoyan worked with me on developing the diagnostic tools in Bean Machine (see https://beanmachine.org/docs/overview/tutorials/Coin_flipping/CoinFlipping/ for an example of a deployed tool). She helped debug, review, and guided development of the tools and I think she will be quite helpful for developing and maintaining more diagnostic tools in ArviZ.

**Comment by horizon-blue** [comment]
Thanks for nominating me. @ndmlny-qs. Yes, I accept the nomination.

**Comment by zaxtax** [comment]
@OriolAbril when does a vote typically happen?

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome!

Can you reach out to arvizdevs (at) gmail (dot) com with the email you'd like us to use when adding you to the ArviZ slack? 

I will also open an issue to this repo to add you to https://www.arviz.org/en/latest/our_team.html#recurrent-contributors. Do you prefer we use your name+surname, github handle...? We generally use name+surname but it is nor required

**Comment by horizon-blue** [comment]
That's great to hear! Thanks for the approval. I just reached out with my email address. 

Regarding the listings, using my name+surname (i.e. Xiaoyan Wang) sounds good to me.

**Comment by OriolAbril** [comment]
Invite sent and PR opened, I'll close and lock the issue now.
