### ISSUE TITLE
Nominate hyunjimoon as recurrent contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#31]
I'd like to nominate @hyunjimoon to be a recurrent contributor at ArviZ.

To @hyunjimoon:

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) role.

---

To ArviZ team members:

We are coordinating to work on SBC related features. Being a recurrent contributor would make it easier to coordinate and accelerate potential improvements.

**Comment by hyunjimoon** [comment]
Thanks for the nomination, Oriol. I am thankful to arviz members for providing a python platform to develop SBC.

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome!

Can you reach out to arvizdevs (at) gmail (dot) com with the email you'd like us to use when adding you to the ArviZ slack?

I will also open a PR to this repo to add you to https://www.arviz.org/en/latest/our_team.html#recurrent-contributors. I am not sure what you'd like us to use though, Hyunji Moon, Angie.H Moon, something else? We generally default to name+surname but neither the content nor the order are required to be this one.

**Comment by hyunjimoon** [comment]
Mail sent and I would go with Angie.H Moon. Thanks!

**Comment by OriolAbril** [comment]
Perfect, thanks. slack invite sent and #33 open. I will now close and lock the issue.
