### ISSUE TITLE
Nominate camillebruckmann as recurrent contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#32]
I'd like to nominate @camillebruckmann to be a recurrent contributor at ArviZ.

To @camillebruckmann:

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) role.

---

To ArviZ team members:

Camille did a PR recently that was expected to be smallish but ended up being huge and navigated the codebase and endgoal changes with close to no help. I think being recurrent contributor would be deserved recognition and might encourage other contributions with even more potential.

**Comment by camillebruckmann** [comment]
Sorry for the delay, thank you Oriol for the nomination! This sounds fantastic, I accept!

**Comment by OriolAbril** [comment]
Very excited to announce that the RV council voted and accepted the nomination! Welcome!

Can you reach out to arvizdevs (at) gmail (dot) com with the email you'd like us to use when adding you to the ArviZ slack?

I will also open a PR to this repo to add you to https://www.arviz.org/en/latest/our_team.html#recurrent-contributors. We default to name+surname so I'll use "Camille Bruckmann" unless you prefer something else like your github handle, it is not required to use name+surname.

**Comment by camillebruckmann** [comment]
"Camille Bruckmann" is great. I've sent the email, looking forward to working with you all :)

**Comment by OriolAbril** [comment]
Thanks, invite to slack sent and #33 open. I'll now close and lock this issue.
