### ISSUE TITLE
Nominate Andy as core contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#36]
I'd like to nominate @ndmlny-qs to be a core contributor at ArviZ.

To @ndmlny-qs:

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the
[core contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#core-contributors)
role.

---

To ArviZ team members:

@ndmlny-qs has been doing a great job with the dashboards and is also helping with evaluating refactorings and potential future designs.

**Comment by ndmlny-qs** [comment]
Thanks, and I accept the nomination.
