### ISSUE TITLE
Nominate Alejandro as core contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#38]
I'd like to nominate @aleicazatti to be a core contributor at ArviZ.

To @aleicazatti:

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the
[core contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#core-contributors)
role.

---

To ArviZ team members:

@aleicazatti is helping incredibly on preliz.

**Comment by aleicazatti** [comment]
Thank you very much! I accept the nomination.
