### ISSUE TITLE
Nominate Tomas as core contributor

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#43]
I'd like to nominate @tomicapretto to be a core contributor at ArviZ.

To @tomicapretto:

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [core contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#core-contributors) role.

---

To ArviZ team members:

It was probably an oversight on our side not to nominate him earlier. @tomicapretto refactored and updated the kde functionality, which was a huge improvement on one of our core functionalities. And lately he has also been very active in refactoring discussions and will host a sprint at PyData.

**Comment by tomicapretto** [comment]
I gave a thumbs up but just realized the issue says "commenting on this issue" so I'll do that: I accept!

**Comment by OriolAbril** [comment]
Sorry for the slow voting process. Happy to report the nomination has been accepted!! I will open a PR to update https://www.arviz.org/en/latest/our_team.html and also send you and invitation to the arviz-devs github organization.
