### ISSUE TITLE
Link from NumFOCUS to arviz ends up on old version of website

### ISSUE THREAD

**Issue by hamogu** [arviz-devs/arviz-project#46]
### Describe the problem

I'm looking at the NumFOCUS page for arviz: https://numfocus.org/project/arviz
At the bottom of the page, is a link to the website for the project in the form of three buttons: "contribute code" "website" "donate".
The "website" button links to: https://arviz-devs.github.io/arviz/
When I click on it, that resolves to https://python.arviz.org/en/0.14.0/index.html, which is not the most recent version and carries a warning on the top: "You are not reading the most recent version of this documentation. [v0.16.1](https://python.arviz.org/en/v0.16.1/index.html) is the latest version available."

I don't know if an update is needed here, or on the NumFOCUS side or maybe both, since I don't know how the redirect from https://arviz-devs.github.io/arviz/ to  https://python.arviz.org/en/0.14.0/... works. I'm reporting it here, because I don't know what the solution is, but it may involve asking NumFOCUS to change the link they use on their website, or it might involve updating what https://arviz-devs.github.io/arviz/ points to.

### Expected behaviour

Link the the most recent version (latest) or the most recent stable version (stable): https://python.arviz.org/en/latest/index.html or maybe better https://python.arviz.org/en/stable/index.html

**Comment by OriolAbril** [comment]
Thanks for reporting, that definitely needs fixing. As that is a project wide page, it should link to https://www.arviz.org/en/latest/ instead of the python library page. I'll make sure the numfocus page is updated.

**Comment by OriolAbril** [comment]
Fixed!
