### ISSUE TITLE
Nominate @n-kall as recurrent contributor

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz-project#47]
I want to nominate @n-kall to be a recurrent contributor at ArviZ.

To @n-kall:

Following our [governance doc](https://www.arviz.org/en/latest/governance/processes.html#new-contributor-nominations-and-confirmation-process), the next step is for you  to accept the nomination which you can do commenting on this issue. If you accept the nomination, there will be a [council vote](https://www.arviz.org/en/latest/governance/processes.html#voting-process) (in private) and we'll publish the result here.

In case it helps or you are still wondering, `arviz.org` has a description of the [recurrent contributor](https://www.arviz.org/en/latest/governance/community_architecture.html#recurrent-contributors) role. Also, don't hesitate to ask any question you might have in this same thread.

---

To ArviZ team members:

@n-kall should join the team because he has been working on prior sensitivity diagnostics (he has a PR open to include this in ArviZ). He is also working on other aspects of the Bayesian workflow and priors, so the project could benefit from his expertise.

**Comment by n-kall** [comment]
Thanks @aloctavodia, I accept the nomination as recurrent contributor  at ArviZ

**Comment by aloctavodia** [comment]
The nomination has been accepted!
