### ISSUE TITLE
2024 Random Variables Council election

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-project#49]
It has been 4 years since the first RV council election which means our 4 year term has finished and we must hold new elections.

The first step is nominating candidates which will happen in this issue during the next two weeks (that is, at least until April 26th). Eligibility criteria and nomination process are described in the [governance page](https://www.arviz.org/en/latest/governance/processes.html#council-selection-process), I am also pasting it here:

> **Eligibility**
>
> * Must be core contributor for at least one year
>
> **Nominations**
>
> * Nominations are taken over a public GitHub issue ticket over the course of 2 weeks.
> * Only Core Contributors may nominate folks
> * Self Nominations are allowed
> * At the conclusion of the 2 weeks, the list of nominations is posted on the ticket and this ticket is closed.

All progress will be tracked both here in this issue and in https://www.arviz.org/en/latest/elections/ArviZ_2024.html which will also serve as historical record.

**Comment by OriolAbril** [comment]
tagging @arviz-devs/core-contributors so everyone is notified

**Comment by ColCarroll** [comment]
I nominate @OriolAbril , @sethaxen , and @aloctavodia

**Comment by OriolAbril** [comment]
I accept my nomination.

I also nominate @ColCarroll @ahartikainen and @ndmlny-qs

**Comment by ahartikainen** [comment]
I accept my nomination

**Comment by sethaxen** [comment]
I accept my nomination

**Comment by ColCarroll** [comment]
I accept my nomination

**Comment by aloctavodia** [comment]
I accept my nomination

**Comment by OriolAbril** [comment]
Closing the nomination period. Will send the list of candidates to numfocus moderator so they can create and share the voting form with all team members.

**Comment by OriolAbril** [comment]
Voting period has finished, with a total of 16 people voting. The results are the following:

| Vote | Oriol Abril Pla | Ari Hartikainen | Seth Axen | Colin Carroll | Andy Maloney | Osvaldo Martin | 
|---|---|---|---|---|---|---|
| Yes | 14 | 12 | 14 | 15 | 8 | 14 | 
| Neutral | 2 | 4 | 2 | 1 | 8 | 2 | 
| No | 0 | 0 | 0 | 0 | 0 | 0 | 

Now that voting has finished we move to the 2nd step in the [election process](https://www.arviz.org/en/latest/governance/processes.html#election-process):

> Candidates are evaluated independently, each candidate having 60% or more of yes votes and less or equal than 20% of no votes is chosen. If the council resulting from all accepted candidates matches all conditions described in [this section](https://www.arviz.org/en/latest/governance/community_architecture.html#council-description) all candidates are confirmed and the election process stops here.

As there are 16 votes, chosen candidates must have 10 or more yes votes and no more than 3 no votes. Consequently, all candidates but Andy are chosen, provided the mentioned conditions are met.

The referenced conditions are:

> The Council will have between 4 and 7 members. No more than 2 Council Members can report to one person or company (including Institutional Partners) through employment or contracting work (including the reportee, i.e. the reportee + 1 is the max).

The council formed by Ari, Seth, Colin, Osvaldo and I has between 4 and 7 members, and only Osvaldo and I share an employer (out of the multiple we both have), so there are no more than 2 Council Members reporting to one person or company. Thus, the council is elected and the election stops here.

I will leave this open for a couple days in case I have missed something or someone wants to report any irregularity. After that I will start updating the website and permissions.
